---
- hosts: 172.31.82.213
  become: yes
  tasks:
  - name: i want to install git
    apt: 
      name: git
      statee: present

  - name: i want to install tree
    apt:
      name: tree
      state: present

  - name: i want to install wget
    apt:
      name: wget
      state: present
                 