---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install apache on ubuntu node
    apt: 
      name: apache2
      state: absent
  - name: i want to install tree
    apt:
      name: tree
      state: absent
  - name:
    apt: 
      name: git
      state: present